### ISSUE TITLE
Upgrade SSN/Org. no-validator

### ISSUE THREAD

**Issue by olssonm** [helsingborg-stad/modularity-resource-booking#1]
Hello!

I notices that this project uses one of my packages ([olssonm/identity-number](https://github.com/olssonm/identity-number)) – which has been discontinued.

Should still work via composer, however, I would upgrade to my new package [olssonm/swedish-entity](https://github.com/olssonm/swedish-entity) as soon as possible. Should only take a few minutes (new namespace and a slightly different pattern).

I began writing a PR to upgrade for you, but ran into some issues as to have the composer dependancy directory (`/vendor`) is committed to Git and didn't want to accidentally break anything as I can't reliably test this package 🙂

**Comment by sebastianthulin** [comment]
Hi! Thank you for you work on this, really grate! We do not intend to further develop this product at this moment. We will make shure to use your new package in the future.

**Comment by olssonm** [comment]
Gotcha – great! Closing...
